# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'RxSwiftDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'RxSwift'
pod 'RxCocoa'
pod 'RxDataSources'
pod 'SnapKit'

  # Pods for RxSwiftDemo

  target 'RxSwiftDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwiftDemoUITests' do
    # Pods for testing
  end

end
